# utilities
# pytest
[tool.pytest.ini_options]
addopts = "-ra --showlocals"
testpaths = "tests"
xfail_strict = true

# flakehell
[tool.flakehell]
format = "colored"
max_line_length = 99
show_source = true
whitelist = "whitelist.txt"
baseline = "baseline.txt"

# list of plugins and rules for them
[tool.flakehell.plugins]
"flake8-*" = ["+*"]
flake8-docstrings = ["+*","-D10*"]
flake8-spellcheck = ["-*"]
flake8-isort = ["-*"]
mccabe = ["+*"]
pep8-naming = ["-*"]
pycodestyle = ["+*","-E302","-E305"]
pyflakes = ["+*","-F401"]
pylint = ["+*"]
wemake-python-styleguide = ["+*","-WPS111","-WPS201","-WPS210","-WPS235","-WPS430","-WPS433"]
# black
[tool.black]
line-length = 99
